### ISSUE TITLE
VS 2022 Support

### ISSUE THREAD

**Issue by mariohuq** [tcbhat/cpptripleslash#4]
Please add support for Visual Studio 2022

**Comment by mariohuq** [comment]
[Here](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) is migration guide

**Comment by tcbhat** [comment]
Added support [here](https://marketplace.visualstudio.com/items?itemName=tcbhat.CppTripleSlash2022)
